// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKTxz3qGD3l-OTRYBrPxBLrNNVRyq50F8',
    appId: '1:105257645633:web:be3cd7f04784a837b178c0',
    messagingSenderId: '105257645633',
    projectId: 'md-rashedul-islam-portfo-51322',
    authDomain: 'md-rashedul-islam-portfo-51322.firebaseapp.com',
    storageBucket: 'md-rashedul-islam-portfo-51322.firebasestorage.app',
    measurementId: 'G-VS0TLVG2CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1VxJl4QJPUGiJzDVClMOIQ_d5TYQXkmc',
    appId: '1:105257645633:android:316763cc00ed56b5b178c0',
    messagingSenderId: '105257645633',
    projectId: 'md-rashedul-islam-portfo-51322',
    storageBucket: 'md-rashedul-islam-portfo-51322.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv8jZJFjnapjrGlg_3XunSKQPF4Xe7zbU',
    appId: '1:105257645633:ios:bc825ee5d9b3f1abb178c0',
    messagingSenderId: '105257645633',
    projectId: 'md-rashedul-islam-portfo-51322',
    storageBucket: 'md-rashedul-islam-portfo-51322.firebasestorage.app',
    iosBundleId: 'com.rashedul.portfolio.portfolioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKTxz3qGD3l-OTRYBrPxBLrNNVRyq50F8',
    appId: '1:105257645633:web:e5946e512dc534c1b178c0',
    messagingSenderId: '105257645633',
    projectId: 'md-rashedul-islam-portfo-51322',
    authDomain: 'md-rashedul-islam-portfo-51322.firebaseapp.com',
    storageBucket: 'md-rashedul-islam-portfo-51322.firebasestorage.app',
    measurementId: 'G-RJMPN9WZ1N',
  );
}
